tmp:
    seq-sim:
        - a
        - uniprot:
            - a
        - tair:
            - a
    domain:
        - iprs:
            - a
    mixed-meth:
        - preprocess:
            - fa:
                - a
log:
    - a
gaf:
  - raw:
      - a
  - non_red:
      - a
  - agg:
      - a
  - uniq:
      - a
input:
    - a
