tmp:
    seq-sim:
        - a
        - uniprot:
            - a
        - tair:
            - a
    domain:
        - iprs:
            - a
            - split:
            - temp:
    mixed-meth:
        - preprocess:
            - blast:
                - temp:
                    # - fa:
                    #     - a
                    # - blast:
                    #     - a
        - argot2.5:
            - blast:
                - a
            - hmmer:
                - a
            - results:
                - a
            - html:
                - a
        - pannzer:
            - blast:
                - a
            - results:
                - a
            - conf:
                - a
        - fanngo:
            - split:
                - a
logs:
  - a
gaf:
  - b.raw_gaf:
    - a
  - d.non_red_gaf:
    - a
  - e.agg_data:
    - a
  - c.uniq_gaf:
    - a
  - a.mm_gaf:
    - a
input:
    - split: