---
data:
  seq-sim:
    TAIR:
      basename:     At.TAIR10
      basedir:      data/data/seq-sim/tair
      tmpdir:       tmp/seq-sim/tair
      gaf:          gaf/At.TAIR10
      metadata:
        date:       ''
        version:    TAIR10
        species:    Arabidopsis
    uniprot:
      basename:     Plant.UniProt.hc
      basedir:      data/data/seq-sim/uniprot
      tmpdir:       tmp/seq-sim/uniprot
      cleaning:
        #asdsadsadas
        sel_tax:
        - '15368'
        - '29760'
        - '3055'
        - '3218'
        - '3694'
        - '3702'
        - '3847'
        - '39947'
        - '4081'
        - '4558'
        omit_tax:
        - '4577'
      metadata:
        version:    '2018-02-26'
        species:    Plants
  domain:
    tmpdir:         tmp/domain/iprs
    tool:
        name:       Interproscan5
        version:    5.25-64.0
  mixed-meth:
      preprocess:
        hmmerdb:    mixed-meth/data/pfamdb/Pfam-A.hmm
        num_seqs: '10000'
        blast_out: tmp/mixed-meth/preprocess/blast
        uniprot_db: mixed-meth/data/blastdb/uniprot_2017_07.sel
        fa_path: tmp/mixed-meth/preprocess/fa
  go:
    gaf_cols:       data/data/cols/gaf_cols.txt
    obo:            data/data/go/go.obo
    evidence_codes:
      omitted:
      - IEA
      - ND
      - NAS

software:
  blast:
    bin:            data/software/blast-2.6.0+/bin
    num_threads:    4
    evalue:         10e-10
    opt_params:
    - "-max_target_seqs"
    - '10'
    cols:           data/data/cols/blast_cols.txt
  iprs:
    path:           data/software/interproscan-5.25-64.0
    cols:           data/data/cols/iprs_cols.txt
    options:
      - -cpu 4
  hmmer:
    path:           software/hmmer-3.1b2-linux-intel-x86_64/binaries
    cpu:            16
logging:
  file_name:        gomap.log
  format:           "%(levelname)s [%(asctime)s] %(message)s"
  formatTime:       "%Y-%m-%d %H:%M"
  level:            DEBUG
pipeline:
  config_file:      pipeline.json
  version:          '0.2'
  name:             GO-MAP
  pipeline_loc:     "/opt/GO-MAP"
  dir_struct:       "config/dirs.yml"
input:
  workdir:          "/workdir"
gaf:
  raw_dir:          gaf/raw
  non_red_dir:      gaf/non_red
  agg_dir:          gaf/agg
  uniq_dir:         gaf/uniq
